export const DefaultTheme = {
    background: "#58636b",
    componentBackground: '#37394a',
    cardBackground: '#30313c',
    cardBorderColor: '#8e24aa',
    color: 'white',
    inverseFontColor: '#58636b',
    fontFamilyHeader: 'AsepriteFont',
    fontFamilyRegular: 'AsepriteFont',
    fontSizeChip: 'x-large',
    fontSizeRegular: 'xx-large',
    fontSizeHeading: 'xxx-large',
    fontSizeMenuItem: '20px',
    borderColor: 'white',
    disabledColor: '#6d708b',
    controlBorderColor: 'white',
    inverseBackgroundColor: 'white',
    warningBackgroundColor: '#fafd0c', 
    successBackgroundColor: '#4cad51', 
    errorBackgroundColor: '#b50e06', 
    informationBackgroundColor: '#001ad6', 
    activeBackgroundColor: 'white',
    activeColor: 'black',
    popupModalColor: '#484545',
    colorPalette: {
        green: '#5eb459',
        green1: '#4b8129',
        orange: '#9f7517',
        greenShadow: '#1c3539',
        yellow: '#fafd0c',
        yellowShadow: '#333832',
        red: '#b50e06',
        redShadow: '#2f1930',
        pink: '#f03ef3',
        pinkShadow: '#490f4a',
        blue: '#001ad6',
        blueShadow: '#021282',
    },
};
  